/** Liste de pays (ISO 3166-1 alpha-2) pour le sélecteur de facturation. */
export const PAYS_PAIEMENT: Array<{ code: string; libelle: string }> = [
  { code: 'DE', libelle: 'Allemagne' },
  { code: 'DZ', libelle: 'Algérie' },
  { code: 'BE', libelle: 'Belgique' },
  { code: 'BJ', libelle: 'Bénin' },
  { code: 'BF', libelle: 'Burkina Faso' },
  { code: 'CM', libelle: 'Cameroun' },
  { code: 'CA', libelle: 'Canada' },
  { code: 'CI', libelle: "Côte d'Ivoire" },
  { code: 'ES', libelle: 'Espagne' },
  { code: 'US', libelle: 'États-Unis' },
  { code: 'FR', libelle: 'France' },
  { code: 'GA', libelle: 'Gabon' },
  { code: 'GH', libelle: 'Ghana' },
  { code: 'GN', libelle: 'Guinée' },
  { code: 'IT', libelle: 'Italie' },
  { code: 'ML', libelle: 'Mali' },
  { code: 'MA', libelle: 'Maroc' },
  { code: 'NE', libelle: 'Niger' },
  { code: 'NG', libelle: 'Nigeria' },
  { code: 'NL', libelle: 'Pays-Bas' },
  { code: 'PT', libelle: 'Portugal' },
  { code: 'GB', libelle: 'Royaume-Uni' },
  { code: 'SN', libelle: 'Sénégal' },
  { code: 'CH', libelle: 'Suisse' },
  { code: 'TG', libelle: 'Togo' },
  { code: 'TN', libelle: 'Tunisie' },
];
